apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: content-marketing
    tier: frontend
  name: content-marketing-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: content-marketing
      tier: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: content-marketing
        tier: frontend
    spec:
      containers:
        - env:
            - name: LOGLEVEL
              value: error
            - name: PORT
              value: "8080"
            - name: ENV
              value: production
            - name: HTTP_TIMEOUT
              value: "2000"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          image: gcr.io/core-ssp/github.com/condigolabs/content-marketing:cbeeb3c
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 2
          name: content-marketing-container
          ports:
            - containerPort: 8080
              name: http-server
              protocol: TCP
            - containerPort: 3000
              name: debug
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 2
            successThreshold: 2
            timeoutSeconds: 2
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /var/secrets/google
              name: google-cloud-key
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
           claimName: references-data-claim
           readOnly: true
        - name: google-cloud-key
          secret:
            defaultMode: 420
            secretName: core-main-key